# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

schedules:
- cron: '50 9 * * Mon-Fri Atlantic/Canary'
  displayName: 'Scheduled build'
  branches:
    include:
    - master
  always: 'false'

pool:
  name: 'TecConnect50Pool'

steps:
- script: echo Starting Devops Tests!
  displayName: 'Starting Devops Tests'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  condition: eq(variables.Build,'true')
  inputs:
    command: 'build'
    projects: 'TodoApi.csproj'
