# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: 'TecConnect50Pool'

steps:
- script: echo Starting Devops Tests!
  displayName: 'Starting Devops Tests'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'wwwroot'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  condition: and(succeeded(), eq(variables.Build,'true'))
  inputs:
    command: 'build'
    projects: 'TodoApi.csproj'
