# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: 'TecConnect50Pool'

steps:
- script: echo Starting Devops Tests!
  displayName: 'Starting Devops Tests'

- script: |
    echo SCRIPT1
    echo END SCRIPT1
  displayName: 'SCRIPT1'
  condition: eq(variables.Build,'true')

- script: |
    echo SCRIPT2
    echo END SCRIPT2
  displayName: 'SCRIPT2'
  condition: and(succeeded(), eq(variables.Build,'true'))

- script: |
    echo SCRIPT3
    echo END SCRIPT3
  displayName: 'SCRIPT3'
  condition: eq(variables.Build,'true')

- task: DotNetCoreCLI@2
  displayName: 'Build'
  condition: and(succeeded(), eq(variables.Build,'true'))
  inputs:
    command: 'build'
    projects: 'TodoApi.csproj'
