# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: 'TecConnect50Pool'

variables:
  Version.MajorMinor: 1.1
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]

steps:
- script: echo Starting Devops Tests!
  displayName: 'Starting Devops Tests'

- script: |
    echo Version.MajorMinor = $(Version.MajorMinor)
    echo Version.Revision = $(Version.Revision)
  displayName: 'Show Version Variables'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  condition: eq(variables.Build,'true')
  inputs:
    command: 'build'
    projects: 'TodoApi.csproj'
